/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.fundamentals.consumer;

import org.junit.jupiter.api.Test;

class ConsumerDbAppTest {
    @Test void appHasAGreeting() {
        ConsumerDbApp classUnderTest = new ConsumerDbApp();
    }
}
