/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.fundamentals.consumer;

import kafka.fundamentals.producer.ProducerApp;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ProducerAppTest {
    @Test void appHasAGreeting() {
        ProducerApp classUnderTest = new ProducerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
